---
title: "Visualización de datos del Covid-19"
author: "Bryan Velicka Leka y Franco Manuel García Dos Santos"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---


## Introducción

En este documento analizaremos y visualizaremos datos sobre el covid tomados hasta la fecha.

## Paso 1 --> Preprocesado

#1.  
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
covid_19_data <- read_csv("covid_19_data.csv")
#View(covid_19_data)

```

#2.
```{r}

datacovid19 <- covid_19_data %>%
                 select(-c(1,3,5))

ind_c <- which(datacovid19$`Country/Region`=="Mainland China")
ind_p <- which(datacovid19$`Country/Region`=="occupied Palestinian territory")

datacovid19$`Country/Region`[ind_c] <- "China"
datacovid19$`Country/Region`[ind_p] <- "Palestina"

datacovid19

datacovid19_por_dia <- datacovid19 %>%
                       group_by(`Country/Region`, ObservationDate) %>%
                       summarise_at(c("Confirmed", "Deaths", "Recovered"), sum)

#datacovid19_por_dia <- datacovid19 %>%
#                       group_by(`Country/Region`, ObservationDate) %>%
#                       summarise_all(list(sum))

```

#3.
```{r}

convertir_a_fecha <- function(ds){
  
  getAño <- function(x){
    strsplit(x,"/")[[1]][[3]]
  }
  getMes <- function(x){
    strsplit(x,"/")[[1]][[1]]
  }
  getDia <- function(x){
    strsplit(x,"/")[[1]][[2]]
  }

  ds$año <- sapply(ds$ObservationDate, getAño)
  ds$mes <- sapply(ds$ObservationDate, getMes)
  ds$dia <- sapply(ds$ObservationDate, getDia)

  ds$ObservationDate <- 
      as.Date( paste(ds$año,"-",ds$mes,"-",ds$dia, sep = "") , "%Y-%m-%d")
  
  ds_with_date <- ds
  
  return(ds_with_date)
  
}

#------------------------------------------------------------------------#

datacovid19_por_dia_Spain <- datacovid19_por_dia %>%
                            filter( `Country/Region`=="Spain" )

datacovid19_por_dia_Spain <- convertir_a_fecha(datacovid19_por_dia_Spain)

datacovid19_por_dia_Spain <- datacovid19_por_dia_Spain %>%
  group_by(ObservationDate) %>%
  arrange(ObservationDate) %>%
  select(-c(1,6,7,8))

names(datacovid19_por_dia_Spain)[1] <- "Date"

datacovid19_por_dia_Spain

```


## Paso 2 --> Visualización

#1. Visualizar las defunciones, los casos confirmados, y los recuperados por día (acumulados)
```{r}

g1 <- ggplot(datacovid19_por_dia_Spain, aes(x=Date, y=Deaths))
g1 + geom_line()



```



